version: "3"

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=qwerty123
    image: postgres:10.3
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2.1
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  elasticsearch:
    environment:
        - discovery.type=single-node
    image: elasticsearch:2.4.5
    ports:
      - 9200:9200
      - 9300:9300

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    depends_on:
      - sidekiq
      - elasticsearch
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/app

volumes:
  postgres:
  redis:
