default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tcc

# test:
#   <<: *default
#   database: tcc_test
#
# production:
#   <<: *default
#   database: tcc_production
  username: gabriel
  # password: <%= ENV['TCC_DATABASE_PASSWORD'] %>
  password:
